from dataclasses import dataclass
from decimal import Decimal


@dataclass
class FutureSymbol:
    symbol: str
    exchange: str
    name: str
    multiplier: float | str = ""  # ib_insync default is '' for none here
    delayed: bool = False


def generateFuturesMapping() -> dict[str, FutureSymbol]:
    """Generate mapping of:
        - future symbol => exchange, name of future
    using the IBKR margin tables (for common exchanges we want at least).

    The values should be fairly static, so we just cache a manual run as
    the global FUTS_EXCHANGE in this file."""
    import pandas as pd

    futs = pd.read_html("https://www.interactivebrokers.com/en/index.php?f=26662")  # type: ignore
    fs = {}
    for ex in futs:
        for idx, row in ex.iterrows():
            # Note: we don't use the name of the columns because the IBKR tables
            #       use different table row names per section, which is annoying,
            #       but their orders remain stable across tables.
            exchange = row[0]
            symbol = row[1]
            name = row[2]
            if exchange in {
                "CBOT",
                "CFE",
                "CME",
                "CMECRYPTO",
                "COMEX",
                "GLOBEX",
                "ICECRYPTO",
                "ICEUS",
                "NYBOT",
                "NYSELIFFE",
                "NYMEX",
                "SMFE",
            }:
                # why setdefault()? Because we only want the FIRST TIME we see a symbol to generate
                # an entry here. This page as additional tables after the ones we want and we DO NOT WANT
                # the final "time at exchange" tables to pollute our previously-populated correct values.
                fs.setdefault(
                    row[1], FutureSymbol(symbol=symbol, exchange=exchange, name=name)
                )

    return fs


# simple mapping from name of future to exchange for future.
# Used for generating ibkr api Future Contract specification since
# each symbol must have an exchange declared.
FUTS_EXCHANGE = {
    "10Y": FutureSymbol(
        symbol="10Y",
        exchange="CBOT",
        name="10 YEAR MICRO TREASURY YIELD",
        multiplier="",
        delayed=False,
    ),
    "2YY": FutureSymbol(
        symbol="2YY",
        exchange="CBOT",
        name="2 YEAR MICRO TREASURY YIELD",
        multiplier="",
        delayed=False,
    ),
    "30Y": FutureSymbol(
        symbol="30Y",
        exchange="CBOT",
        name="30 YEAR MICRO TREASURY YIELD",
        multiplier="",
        delayed=False,
    ),
    "5YY": FutureSymbol(
        symbol="5YY",
        exchange="CBOT",
        name="5 YEAR MICRO TREASURY YIELD",
        multiplier="",
        delayed=False,
    ),
    "AIGCI": FutureSymbol(
        symbol="AIGCI",
        exchange="CBOT",
        name="BLOOMBERG COMMODITY INDEX",
        multiplier="",
        delayed=False,
    ),
    "AC": FutureSymbol(
        symbol="AC", exchange="CBOT", name="ETHANOL -CME", multiplier="", delayed=False
    ),
    "KE": FutureSymbol(
        symbol="KE",
        exchange="CBOT",
        name="HARD RED WINTER WHEAT -KCBOT-",
        multiplier="",
        delayed=False,
    ),
    "MTN": FutureSymbol(
        symbol="MTN",
        exchange="CBOT",
        name="MICRO ULTRA 10-YEAR U.S TREASURY NOTE",
        multiplier="",
        delayed=False,
    ),
    "MWN": FutureSymbol(
        symbol="MWN",
        exchange="CBOT",
        name="MICRO ULTRA US TREASURY BOND",
        multiplier="",
        delayed=False,
    ),
    "MYM": FutureSymbol(
        symbol="MYM",
        exchange="CBOT",
        name="MICRO E-MINI DOW JONES INDUSTRIAL AVERAGE INDEX",
        multiplier="",
        delayed=False,
    ),
    "DJUSRE": FutureSymbol(
        symbol="DJUSRE",
        exchange="CBOT",
        name="DOW JONES US REAL ESTATE INDEX",
        multiplier="",
        delayed=False,
    ),
    "TN": FutureSymbol(
        symbol="TN",
        exchange="CBOT",
        name="ULTRA 10-YEAR US TREASURY NOTE",
        multiplier="",
        delayed=False,
    ),
    "TWE": FutureSymbol(
        symbol="TWE",
        exchange="CBOT",
        name="20-YEAR U.S. TREASURY BOND",
        multiplier="",
        delayed=False,
    ),
    "UB": FutureSymbol(
        symbol="UB",
        exchange="CBOT",
        name="ULTRA TREASURY BOND",
        multiplier="",
        delayed=False,
    ),
    "YC": FutureSymbol(
        symbol="YC",
        exchange="CBOT",
        name="MINI SIZED CORN FUTURES",
        multiplier="",
        delayed=False,
    ),
    "YK": FutureSymbol(
        symbol="YK",
        exchange="CBOT",
        name="MINI SIZED SOYBEAN FUTURES",
        multiplier="",
        delayed=False,
    ),
    "YW": FutureSymbol(
        symbol="YW",
        exchange="CBOT",
        name="MINI SIZED WHEAT FUTURES",
        multiplier="",
        delayed=False,
    ),
    "YIA": FutureSymbol(
        symbol="YIA",
        exchange="CBOT",
        name="1-YEAR ERIS SOFR SWAP FUTURES",
        multiplier="",
        delayed=False,
    ),
    "YIC": FutureSymbol(
        symbol="YIC",
        exchange="CBOT",
        name="3-YEAR ERIS SOFR SWAP FUTURES",
        multiplier="",
        delayed=False,
    ),
    "YID": FutureSymbol(
        symbol="YID",
        exchange="CBOT",
        name="4-YEAR ERIS SOFR SWAP FUTURES",
        multiplier="",
        delayed=False,
    ),
    "YIT": FutureSymbol(
        symbol="YIT",
        exchange="CBOT",
        name="2-YEAR ERIS SOFR SWAP FUTURES",
        multiplier="",
        delayed=False,
    ),
    "YIW": FutureSymbol(
        symbol="YIW",
        exchange="CBOT",
        name="5-YEAR ERIS SOFR SWAP FUTURES",
        multiplier="",
        delayed=False,
    ),
    "YM": FutureSymbol(
        symbol="YM",
        exchange="CBOT",
        name="E-MINI DOW JONES INDUSTRIAL AVERAGE",
        multiplier="",
        delayed=False,
    ),
    "Z3N": FutureSymbol(
        symbol="Z3N",
        exchange="CBOT",
        name="3 YEAR US TREASURY NOTE",
        multiplier="",
        delayed=False,
    ),
    "ZB": FutureSymbol(
        symbol="ZB",
        exchange="CBOT",
        name="US TREASURY BOND",
        multiplier="",
        delayed=False,
    ),
    "ZC": FutureSymbol(
        symbol="ZC", exchange="CBOT", name="CORN FUTURES", multiplier="", delayed=False
    ),
    "ZF": FutureSymbol(
        symbol="ZF",
        exchange="CBOT",
        name="5 YEAR US TREASURY NOTE",
        multiplier="",
        delayed=False,
    ),
    "ZL": FutureSymbol(
        symbol="ZL",
        exchange="CBOT",
        name="SOYBEAN OIL FUTURES",
        multiplier="",
        delayed=False,
    ),
    "ZM": FutureSymbol(
        symbol="ZM",
        exchange="CBOT",
        name="SOYBEAN MEAL FUTURES",
        multiplier="",
        delayed=False,
    ),
    "ZN": FutureSymbol(
        symbol="ZN",
        exchange="CBOT",
        name="10 YEAR US TREASURY NOTE",
        multiplier="",
        delayed=False,
    ),
    "ZO": FutureSymbol(
        symbol="ZO", exchange="CBOT", name="OAT FUTURES", multiplier="", delayed=False
    ),
    "ZQ": FutureSymbol(
        symbol="ZQ", exchange="CBOT", name="-", multiplier="", delayed=False
    ),
    "ZR": FutureSymbol(
        symbol="ZR",
        exchange="CBOT",
        name="ROUGH RICE FUTURES",
        multiplier="",
        delayed=False,
    ),
    "ZS": FutureSymbol(
        symbol="ZS",
        exchange="CBOT",
        name="SOYBEAN FUTURES",
        multiplier="",
        delayed=False,
    ),
    "ZT": FutureSymbol(
        symbol="ZT",
        exchange="CBOT",
        name="2 YEAR US TREASURY NOTE",
        multiplier="",
        delayed=False,
    ),
    "ZW": FutureSymbol(
        symbol="ZW", exchange="CBOT", name="WHEAT FUTURES", multiplier="", delayed=False
    ),
    "IBXXIBHY": FutureSymbol(
        symbol="IBXXIBHY",
        exchange="CFE",
        name="IBOXX ISHARES $ HIGH YIELD CORPORATE BOND INDEX TR",
        multiplier="",
        delayed=False,
    ),
    "IBXXIBIG": FutureSymbol(
        symbol="IBXXIBIG",
        exchange="CFE",
        name="IBOXX ISHARES $ INVESTMENT GRADE CORPORATE BOND INDEX TR",
        multiplier="",
        delayed=False,
    ),
    "VIX": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX",
        multiplier="",
        delayed=False,
    ),
    "VXM": FutureSymbol(
        symbol="VXM",
        exchange="CFE",
        name="MINI CBOE VOLATILITY INDEX FUTURES",
        multiplier="",
        delayed=False,
    ),
    "AUD": FutureSymbol(
        symbol="AUD", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "GBP": FutureSymbol(
        symbol="GBP", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "CAD": FutureSymbol(
        symbol="CAD", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "EUR": FutureSymbol(
        symbol="EUR", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "JPY": FutureSymbol(
        symbol="JPY", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "BRE": FutureSymbol(
        symbol="BRE", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "MXP": FutureSymbol(
        symbol="MXP", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "NZD": FutureSymbol(
        symbol="NZD", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "RUR *": FutureSymbol(
        symbol="RUR *", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "CHF": FutureSymbol(
        symbol="CHF", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "ZAR": FutureSymbol(
        symbol="ZAR", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "ACDX": FutureSymbol(
        symbol="ACDX", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "AJY": FutureSymbol(
        symbol="AJY", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "BQX": FutureSymbol(
        symbol="BQX",
        exchange="CME",
        name="CME E-MINI NASDAQ BIOTECHNOLOGY",
        multiplier="",
        delayed=False,
    ),
    "BOS": FutureSymbol(
        symbol="BOS",
        exchange="CME",
        name="BOSTON HOUSING INDEX",
        multiplier="",
        delayed=False,
    ),
    "BRR": FutureSymbol(
        symbol="BRR",
        exchange="CME",
        name="CME CF BITCOIN REFERENCE RATE",
        multiplier="",
        delayed=False,
    ),
    "BTCEURRR": FutureSymbol(
        symbol="BTCEURRR",
        exchange="CME",
        name="CME CF BITCOIN-EURO REFERENCE RATE",
        multiplier="",
        delayed=False,
    ),
    "CB": FutureSymbol(
        symbol="CB",
        exchange="CME",
        name="CME CASH-SETTLED BUTTER FUTURES",
        multiplier="",
        delayed=False,
    ),
    "CHI": FutureSymbol(
        symbol="CHI",
        exchange="CME",
        name="CHICAGO HOUSING INDEX",
        multiplier="",
        delayed=False,
    ),
    "CLP": FutureSymbol(
        symbol="CLP", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "CJY": FutureSymbol(
        symbol="CJY", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "CNH": FutureSymbol(
        symbol="CNH", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "CSC": FutureSymbol(
        symbol="CSC", exchange="CME", name="CHEESE", multiplier="", delayed=False
    ),
    "CUS": FutureSymbol(
        symbol="CUS",
        exchange="CME",
        name="HOUSING INDEX COMPOSITE",
        multiplier="",
        delayed=False,
    ),
    "CZK": FutureSymbol(
        symbol="CZK", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "DA": FutureSymbol(
        symbol="DA",
        exchange="CME",
        name="MILK CLASS III INDEX",
        multiplier="",
        delayed=False,
    ),
    "DEN": FutureSymbol(
        symbol="DEN",
        exchange="CME",
        name="DENVER HOUSING INDEX",
        multiplier="",
        delayed=False,
    ),
    "DY": FutureSymbol(
        symbol="DY",
        exchange="CME",
        name="CME DRY WHEY INDEX",
        multiplier="",
        delayed=False,
    ),
    "E7": FutureSymbol(
        symbol="E7", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "EAD": FutureSymbol(
        symbol="EAD", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "ECD": FutureSymbol(
        symbol="ECD", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "ECK": FutureSymbol(
        symbol="ECK", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "EHF": FutureSymbol(
        symbol="EHF", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "EMD": FutureSymbol(
        symbol="EMD",
        exchange="CME",
        name="E-MINI S&P MIDCAP 400 FUTURES",
        multiplier="",
        delayed=False,
    ),
    "NIY": FutureSymbol(
        symbol="NIY",
        exchange="CME",
        name="YEN DENOMINATED NIKKEI 225 INDEX",
        multiplier="",
        delayed=False,
    ),
    "EPZ": FutureSymbol(
        symbol="EPZ", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "ES": FutureSymbol(
        symbol="ES", exchange="CME", name="E-MINI S&P 500", multiplier="", delayed=False
    ),
    "SPXESUP": FutureSymbol(
        symbol="SPXESUP",
        exchange="CME",
        name="E-MINI S&P 500 ESG",
        multiplier="",
        delayed=False,
    ),
    "ESTR": FutureSymbol(
        symbol="ESTR", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "ETHEURRR": FutureSymbol(
        symbol="ETHEURRR",
        exchange="CME",
        name="CME CF ETHER-EURO REFERENCE RATE",
        multiplier="",
        delayed=False,
    ),
    "ETHUSDRR": FutureSymbol(
        symbol="ETHUSDRR",
        exchange="CME",
        name="CME CF ETHER-DOLLAR REFERENCE RATE",
        multiplier="",
        delayed=False,
    ),
    "GSCI": FutureSymbol(
        symbol="GSCI",
        exchange="CME",
        name="S&P-GSCI INDEX",
        multiplier="",
        delayed=False,
    ),
    "GDK": FutureSymbol(
        symbol="GDK",
        exchange="CME",
        name="CLASS IV MILK - 200K LBS",
        multiplier="",
        delayed=False,
    ),
    "GF": FutureSymbol(
        symbol="GF", exchange="CME", name="FEEDER CATTLE", multiplier="", delayed=False
    ),
    "NF": FutureSymbol(
        symbol="NF",
        exchange="CME",
        name="NON FAT DRY MILK INDEX",
        multiplier="",
        delayed=False,
    ),
    "HE": FutureSymbol(
        symbol="HE", exchange="CME", name="LEAN HOGS", multiplier="", delayed=False
    ),
    "HUF": FutureSymbol(
        symbol="HUF", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "IBAA": FutureSymbol(
        symbol="IBAA",
        exchange="CME",
        name="BOVESPA INDEX - USD",
        multiplier="",
        delayed=False,
    ),
    "ILS": FutureSymbol(
        symbol="ILS", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "J7": FutureSymbol(
        symbol="J7", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "KRW": FutureSymbol(
        symbol="KRW", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "LAV": FutureSymbol(
        symbol="LAV",
        exchange="CME",
        name="LAS VEGAS HOUSING INDEX",
        multiplier="",
        delayed=False,
    ),
    "LAX": FutureSymbol(
        symbol="LAX",
        exchange="CME",
        name="LOS ANGELES HOUSING INDEX",
        multiplier="",
        delayed=False,
    ),
    "LBR": FutureSymbol(
        symbol="LBR",
        exchange="CME",
        name="LUMBER FUTURES",
        multiplier="",
        delayed=False,
    ),
    "LE": FutureSymbol(
        symbol="LE", exchange="CME", name="LIVE CATTLE", multiplier="", delayed=False
    ),
    "M2K": FutureSymbol(
        symbol="M2K",
        exchange="CME",
        name="MICRO E-MINI RUSSELL 2000 INDEX",
        multiplier="",
        delayed=False,
    ),
    "M6A": FutureSymbol(
        symbol="M6A", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "M6B": FutureSymbol(
        symbol="M6B", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "M6E": FutureSymbol(
        symbol="M6E", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "MBT": FutureSymbol(
        symbol="MBT", exchange="CME", name="MICRO BITCOIN", multiplier="", delayed=False
    ),
    "MCD": FutureSymbol(
        symbol="MCD", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "MES": FutureSymbol(
        symbol="MES",
        exchange="CME",
        name="MICRO E-MINI S&P 500 STOCK PRICE INDEX",
        multiplier="",
        delayed=False,
    ),
    "MET": FutureSymbol(
        symbol="MET", exchange="CME", name="MICRO ETHER", multiplier="", delayed=False
    ),
    "MIA": FutureSymbol(
        symbol="MIA",
        exchange="CME",
        name="MIAMI HOUSING INDEX",
        multiplier="",
        delayed=False,
    ),
    "MIR": FutureSymbol(
        symbol="MIR", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "MNH": FutureSymbol(
        symbol="MNH", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "MNQ": FutureSymbol(
        symbol="MNQ",
        exchange="CME",
        name="MICRO E-MINI NASDAQ-100 INDEX",
        multiplier="",
        delayed=False,
    ),
    "MSF": FutureSymbol(
        symbol="MSF", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "NKD": FutureSymbol(
        symbol="NKD",
        exchange="CME",
        name="DOLLAR DENOMINATED NIKKEI 225 INDEX",
        multiplier="",
        delayed=False,
    ),
    "NOK": FutureSymbol(
        symbol="NOK", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "NQ": FutureSymbol(
        symbol="NQ",
        exchange="CME",
        name="E-MINI NASDAQ 100",
        multiplier="",
        delayed=False,
    ),
    "NYM": FutureSymbol(
        symbol="NYM",
        exchange="CME",
        name="NEW YORK HOUSING INDEX",
        multiplier="",
        delayed=False,
    ),
    "PJY": FutureSymbol(
        symbol="PJY", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "PLN": FutureSymbol(
        symbol="PLN", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "PSF": FutureSymbol(
        symbol="PSF", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "RF": FutureSymbol(
        symbol="RF", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "RMB": FutureSymbol(
        symbol="RMB", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "RME": FutureSymbol(
        symbol="RME", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "RP": FutureSymbol(
        symbol="RP", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "RS1": FutureSymbol(
        symbol="RS1",
        exchange="CME",
        name="E-MINI RUSSELL 1000 INDEX FUTURES",
        multiplier="",
        delayed=False,
    ),
    "RSG": FutureSymbol(
        symbol="RSG",
        exchange="CME",
        name="E-MINI RUSSELL 1000 GROWTH INDEX FUTURES",
        multiplier="",
        delayed=False,
    ),
    "RSV": FutureSymbol(
        symbol="RSV",
        exchange="CME",
        name="E-MINI RUSSELL 1000 VALUE INDEX FUTURES",
        multiplier="",
        delayed=False,
    ),
    "RTY": FutureSymbol(
        symbol="RTY",
        exchange="CME",
        name="E-MINI RUSSELL 2000 INDEX",
        multiplier="",
        delayed=False,
    ),
    "RY": FutureSymbol(
        symbol="RY", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "SPXDIVAN": FutureSymbol(
        symbol="SPXDIVAN",
        exchange="CME",
        name="S&P 500 DIVIDEND POINTS (ANNUAL) INDEX",
        multiplier="",
        delayed=False,
    ),
    "SDG": FutureSymbol(
        symbol="SDG",
        exchange="CME",
        name="SAN DIEGO HOUSING INDEX",
        multiplier="",
        delayed=False,
    ),
    "SEK": FutureSymbol(
        symbol="SEK", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "SFR": FutureSymbol(
        symbol="SFR",
        exchange="CME",
        name="SAN FRANCISCO HOUSING INDEX",
        multiplier="",
        delayed=False,
    ),
    "SGX": FutureSymbol(
        symbol="SGX", exchange="CME", name="SHORT GILT", multiplier="", delayed=False
    ),
    "SIR": FutureSymbol(
        symbol="SIR", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "SJY": FutureSymbol(
        symbol="SJY", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "SMC": FutureSymbol(
        symbol="SMC",
        exchange="CME",
        name="E-MINI S&P SMALLCAP 600 FUTURES",
        multiplier="",
        delayed=False,
    ),
    "SONIA": FutureSymbol(
        symbol="SONIA", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "SOFR1": FutureSymbol(
        symbol="SOFR1", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "SOFR3": FutureSymbol(
        symbol="SOFR3", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "SVX": FutureSymbol(
        symbol="SVX",
        exchange="CME",
        name="SCHNEIDER ELECTRIC SE",
        multiplier="",
        delayed=False,
    ),
    "TBF3": FutureSymbol(
        symbol="TBF3", exchange="CME", name="-", multiplier="", delayed=False
    ),
    "WDC": FutureSymbol(
        symbol="WDC",
        exchange="CME",
        name="WASHINGTON DC HOUSING INDEX",
        multiplier="",
        delayed=False,
    ),
    "IXB": FutureSymbol(
        symbol="IXB",
        exchange="CME",
        name="MATERIALS SELECT SECTOR INDEX",
        multiplier="",
        delayed=False,
    ),
    "IXE": FutureSymbol(
        symbol="IXE",
        exchange="CME",
        name="ENERGY SELECT SECTOR INDEX",
        multiplier="",
        delayed=False,
    ),
    "IXM": FutureSymbol(
        symbol="IXM",
        exchange="CME",
        name="FINANCIAL SELECT SECTOR INDEX",
        multiplier="",
        delayed=False,
    ),
    "IXI": FutureSymbol(
        symbol="IXI",
        exchange="CME",
        name="INDUSTRIAL SELECT SECTOR INDEX",
        multiplier="",
        delayed=False,
    ),
    "IXT": FutureSymbol(
        symbol="IXT",
        exchange="CME",
        name="TECHNOLOGY SELECT SECTOR INDEX -",
        multiplier="",
        delayed=False,
    ),
    "IXR": FutureSymbol(
        symbol="IXR",
        exchange="CME",
        name="CONSUMER STAPLES SELECT SECTOR INDEX",
        multiplier="",
        delayed=False,
    ),
    "IXRE": FutureSymbol(
        symbol="IXRE",
        exchange="CME",
        name="REAL ESTATE SELECT SECTOR INDEX",
        multiplier="",
        delayed=False,
    ),
    "IXU": FutureSymbol(
        symbol="IXU",
        exchange="CME",
        name="UTILITIES SELECT SECTOR INDEX",
        multiplier="",
        delayed=False,
    ),
    "IXV": FutureSymbol(
        symbol="IXV",
        exchange="CME",
        name="HEALTH CARE SELECT SECTOR INDEX",
        multiplier="",
        delayed=False,
    ),
    "IXY": FutureSymbol(
        symbol="IXY",
        exchange="CME",
        name="CONSUMER DISCRETIONARY SELECT SECTOR INDEX",
        multiplier="",
        delayed=False,
    ),
    "ALI": FutureSymbol(
        symbol="ALI",
        exchange="COMEX",
        name="ALUMINUM INDEX",
        multiplier="",
        delayed=False,
    ),
    "GC": FutureSymbol(
        symbol="GC", exchange="COMEX", name="GOLD", multiplier="", delayed=False
    ),
    "HG": FutureSymbol(
        symbol="HG", exchange="COMEX", name="COPPER INDEX", multiplier="", delayed=False
    ),
    "HRC": FutureSymbol(
        symbol="HRC",
        exchange="COMEX",
        name="HOT-ROLLED COIL STEEL INDEX",
        multiplier="",
        delayed=False,
    ),
    "MGC": FutureSymbol(
        symbol="MGC",
        exchange="COMEX",
        name="E-MICRO GOLD",
        multiplier="",
        delayed=False,
    ),
    "MHG": FutureSymbol(
        symbol="MHG",
        exchange="COMEX",
        name="MICRO COPPER",
        multiplier="",
        delayed=False,
    ),
    "QC": FutureSymbol(
        symbol="QC",
        exchange="COMEX",
        name="COMEX MINY COPPER",
        multiplier="",
        delayed=False,
    ),
    "QI": FutureSymbol(
        symbol="QI",
        exchange="COMEX",
        name="COMEX MINY SILVER",
        multiplier="",
        delayed=False,
    ),
    "QO": FutureSymbol(
        symbol="QO",
        exchange="COMEX",
        name="COMEX MINY GOLD",
        multiplier="",
        delayed=False,
    ),
    "SGC": FutureSymbol(
        symbol="SGC",
        exchange="COMEX",
        name="SHANGHAI GOLD EXCHANGE GOLD BENCHMARK PM PRICE INDEX - CNH FUTURES",
        multiplier="",
        delayed=False,
    ),
    "SGUF": FutureSymbol(
        symbol="SGUF",
        exchange="COMEX",
        name="SHANGHAI GOLD EXCHANGE GOLD BENCHMARK PM PRICE INDEX - USD FUTURES",
        multiplier="",
        delayed=False,
    ),
    "SI": FutureSymbol(
        symbol="SI", exchange="COMEX", name="SILVER INDEX", multiplier="", delayed=False
    ),
    "UX": FutureSymbol(
        symbol="UX",
        exchange="COMEX",
        name="URANIUM INDEX",
        multiplier="",
        delayed=False,
    ),
    "EJ": FutureSymbol(
        symbol="EJ", exchange="ICEUS", name="-", multiplier="", delayed=False
    ),
    "EO": FutureSymbol(
        symbol="EO", exchange="ICEUS", name="-", multiplier="", delayed=False
    ),
    "GB": FutureSymbol(
        symbol="GB", exchange="ICEUS", name="-", multiplier="", delayed=False
    ),
    "RZ": FutureSymbol(
        symbol="RZ", exchange="ICEUS", name="-", multiplier="", delayed=False
    ),
    "ZY": FutureSymbol(
        symbol="ZY", exchange="ICEUS", name="-", multiplier="", delayed=False
    ),
    "MP": FutureSymbol(
        symbol="MP", exchange="ICEUS", name="-", multiplier="", delayed=False
    ),
    "SS": FutureSymbol(
        symbol="SS", exchange="ICEUS", name="-", multiplier="", delayed=False
    ),
    "SY": FutureSymbol(
        symbol="SY", exchange="ICEUS", name="-", multiplier="", delayed=False
    ),
    "LRC30APR": FutureSymbol(
        symbol="LRC30APR",
        exchange="NYBOT",
        name="ICE U.S. CONFORMING 30-YR FIXED MORTGAGE RATE LOCK WEIGHTED APR",
        multiplier="",
        delayed=False,
    ),
    "CC": FutureSymbol(
        symbol="CC", exchange="NYBOT", name="COCOA NYBOT", multiplier="", delayed=False
    ),
    "CT": FutureSymbol(
        symbol="CT", exchange="NYBOT", name="COTTON NO. 2", multiplier="", delayed=False
    ),
    "DX": FutureSymbol(
        symbol="DX", exchange="NYBOT", name="-", multiplier="", delayed=False
    ),
    "NYFANG": FutureSymbol(
        symbol="NYFANG",
        exchange="NYBOT",
        name="NYSE FANG+ INDEX",
        multiplier="",
        delayed=False,
    ),
    "KC": FutureSymbol(
        symbol="KC", exchange="NYBOT", name='COFFEE "C"', multiplier="", delayed=False
    ),
    "OJ": FutureSymbol(
        symbol="OJ",
        exchange="NYBOT",
        name='FC ORANGE JUICE "A"',
        multiplier="",
        delayed=False,
    ),
    "RS": FutureSymbol(
        symbol="RS", exchange="NYBOT", name="CANOLA", multiplier="", delayed=False
    ),
    "SB": FutureSymbol(
        symbol="SB", exchange="NYBOT", name="SUGAR NO. 11", multiplier="", delayed=False
    ),
    "SF": FutureSymbol(
        symbol="SF",
        exchange="NYBOT",
        name="SUGAR #16 112000 LBS",
        multiplier="",
        delayed=False,
    ),
    "BB": FutureSymbol(
        symbol="BB", exchange="NYMEX", name="-", multiplier="", delayed=False
    ),
    "BZ": FutureSymbol(
        symbol="BZ",
        exchange="NYMEX",
        name="BRENT CRUDE OIL - LAST DAY",
        multiplier="",
        delayed=False,
    ),
    "CL": FutureSymbol(
        symbol="CL",
        exchange="NYMEX",
        name="LIGHT SWEET CRUDE OIL",
        multiplier="",
        delayed=False,
    ),
    "HH": FutureSymbol(
        symbol="HH",
        exchange="NYMEX",
        name="NATURAL GAS LAST DAY FINANCIAL FUTURES INDEX",
        multiplier="",
        delayed=False,
    ),
    "HO": FutureSymbol(
        symbol="HO", exchange="NYMEX", name="HEATING OIL", multiplier="", delayed=False
    ),
    "HP": FutureSymbol(
        symbol="HP",
        exchange="NYMEX",
        name="NATURAL GAS PENULTIMATE FINANCIAL FUTURES INDEX",
        multiplier="",
        delayed=False,
    ),
    "MCL": FutureSymbol(
        symbol="MCL",
        exchange="NYMEX",
        name="MICRO WTI CRUDE OIL",
        multiplier="",
        delayed=False,
    ),
    "MHO": FutureSymbol(
        symbol="MHO",
        exchange="NYMEX",
        name="MICRO NY HARBOR ULSD",
        multiplier="",
        delayed=False,
    ),
    "MHNG": FutureSymbol(
        symbol="MHNG",
        exchange="NYMEX",
        name="MICRO HENRY HUB NATURAL GAS",
        multiplier="",
        delayed=False,
    ),
    "MRB": FutureSymbol(
        symbol="MRB",
        exchange="NYMEX",
        name="MICRO RBOB GASOLINE",
        multiplier="",
        delayed=False,
    ),
    "NG": FutureSymbol(
        symbol="NG",
        exchange="NYMEX",
        name="HENRY HUB NATURAL GAS",
        multiplier="",
        delayed=False,
    ),
    "PA": FutureSymbol(
        symbol="PA",
        exchange="NYMEX",
        name="PALLADIUM INDEX",
        multiplier="",
        delayed=False,
    ),
    "PL": FutureSymbol(
        symbol="PL",
        exchange="NYMEX",
        name="PLATINUM INDEX",
        multiplier="",
        delayed=False,
    ),
    "QG": FutureSymbol(
        symbol="QG",
        exchange="NYMEX",
        name="NYMEX MINY NATURAL GAS INDEX",
        multiplier="",
        delayed=False,
    ),
    "QM": FutureSymbol(
        symbol="QM",
        exchange="NYMEX",
        name="NYMEX MINY LIGHT SWEET CRUDE OIL",
        multiplier="",
        delayed=False,
    ),
    "RB": FutureSymbol(
        symbol="RB",
        exchange="NYMEX",
        name="NYMEX RBOB GASOLINE INDEX",
        multiplier="",
        delayed=False,
    ),
    "TT": FutureSymbol(
        symbol="TT",
        exchange="NYMEX",
        name="NYMEX COTTON INDEX",
        multiplier="",
        delayed=False,
    ),
    "M1MSA": FutureSymbol(
        symbol="M1MSA",
        exchange="NYSELIFFE",
        name="MSCI EMERGING MARKETS ASIA NET TOTAL RETURN (NTR)",
        multiplier="",
        delayed=False,
    ),
    "M1EU": FutureSymbol(
        symbol="M1EU",
        exchange="NYSELIFFE",
        name="MSCI EUROPE NTR",
        multiplier="",
        delayed=False,
    ),
    "M1JP": FutureSymbol(
        symbol="M1JP",
        exchange="NYSELIFFE",
        name="THE MSCI JAPAN NTR",
        multiplier="",
        delayed=False,
    ),
    "MXEA": FutureSymbol(
        symbol="MXEA",
        exchange="NYSELIFFE",
        name="MSCI EAFE INDEX",
        multiplier="",
        delayed=False,
    ),
    "MXEF": FutureSymbol(
        symbol="MXEF",
        exchange="NYSELIFFE",
        name="MSCI EMERGING MARKETS INDEX",
        multiplier="",
        delayed=False,
    ),
    "MXUS": FutureSymbol(
        symbol="MXUS",
        exchange="NYSELIFFE",
        name="MSCI USA INDEX",
        multiplier="",
        delayed=False,
    ),
    "10YSME": FutureSymbol(
        symbol="10YSME",
        exchange="SMFE",
        name="SMALL 10YR US TREASURY YIELD",
        multiplier="",
        delayed=False,
    ),
    "2YSME": FutureSymbol(
        symbol="2YSME",
        exchange="SMFE",
        name="SMALL 2YR US TREASURY YIELD",
        multiplier="",
        delayed=False,
    ),
} | {
    # NOTABLE MANUAL EXCEPTIONS TO THE ABOVE:
    # IBKR uses the SAME SYMBOL for bitcoin futures and micro bitcoin futures, with
    # the only difference being the multiplier requirement.
    # We distinguish our usable names via /BTC for full and /MBT for micros.
    "BTC": FutureSymbol(
        symbol="BRR",
        exchange="CME",
        multiplier=5,
        name="CME CF Bitcoin Reference Rate",
    ),
    "MBT": FutureSymbol(
        symbol="BRR",
        exchange="CME",
        multiplier=0.1,
        name="CME CF Micro Bitcoin Reference Rate",
    ),
    # We can't figure out which data package enables VIX access, so use delayed quotes.
    "VIX": FutureSymbol(symbol="VIX", exchange="CFE", name="CBOE Volatility Index"),
    "VXM": FutureSymbol(
        symbol="VXM",
        delayed=True,
        exchange="CFE",
        name="Mini Cboe Volatility Index Futures",
    ),
}

# We have ANOTHER dataset for _different_ futures details.
# The above FUTS_EXCHANGE is the official IBKR symbol to exchange mapping, but we also have some extra
# data we may want to use for showing users various details too.


@dataclass
class FutureDetail:
    symbol: str
    exchange: str
    name: str

    # what this future represents
    size: str

    # exchange months in exchange format of:
    #  Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
    #    F   G   H   J   K   M   N   Q   U   V   X   Z
    months: str

    # Decimal tick per instrument (same for all series)
    tick: Decimal

    # number of decimal points for displaying quotes and placing orders (minimum: 0, maximum 8)
    decimals: int

    # string representing currency value per 'tick' change.
    valuePerTick: str


def buildTickDetail():
    df = pd.read_html("https://futuresonline.com/education/products/specifications/")
    syms = {}

    # first row is their futures symbol to month mapping table, so skip it
    for table in df[1:]:
        for idx, row in table.iterrows():
            digits = Decimal(row.Tick.split()[0])
            valuePerTick = row.Tick.split()[-1]
            syms[row.Symbol] = FutureDetail(
                symbol=row.Symbol,
                name=row.Name,
                tick=digits,
                decimals=-digits.as_tuple().exponent,
                valuePerTick=valuePerTick,
                months=row.Months,
                exchange=row.Exchange,
                size=row.Size,
            )

    return syms


# Note: these are from an EXTERNAL data source, so these symbol names do not _necessarily_ correlate to
#       matching IBKR symbol names, but it's a start.
FUTS_TICK_DETAIL = {
    "6A": FutureDetail(
        symbol="6A",
        exchange="CME",
        name="Aussie Dollar",
        size="100000 AUD",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.00005"),
        decimals=5,
        valuePerTick="$5",
    ),
    "6L": FutureDetail(
        symbol="6L",
        exchange="CME",
        name="Brazilian Real",
        size="100000 BRL",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.00005"),
        decimals=5,
        valuePerTick="$5",
    ),
    "6B": FutureDetail(
        symbol="6B",
        exchange="CME",
        name="British Pound",
        size="62500 GBP",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.0001"),
        decimals=4,
        valuePerTick="$6.25",
    ),
    "PJY": FutureDetail(
        symbol="PJY",
        exchange="CME",
        name="British Pound/Japanese Yen",
        size="125000 GBP",
        months="HMUZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="¥1250",
    ),
    "6C": FutureDetail(
        symbol="6C",
        exchange="CME",
        name="Canadian Dollar",
        size="100000 CAD",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.00005"),
        decimals=5,
        valuePerTick="$5",
    ),
    "E7": FutureDetail(
        symbol="E7",
        exchange="CME",
        name="E-Mini Euro FX",
        size="62500 EUR",
        months="HMUZ",
        tick=Decimal("0.0001"),
        decimals=4,
        valuePerTick="$6.25",
    ),
    "J7": FutureDetail(
        symbol="J7",
        exchange="CME",
        name="E-mini Japanese Yen",
        size="6250000 JPY",
        months="HMUZ",
        tick=Decimal("0.000001"),
        decimals=6,
        valuePerTick="$6.25",
    ),
    "6E": FutureDetail(
        symbol="6E",
        exchange="CME",
        name="Euro FX",
        size="125000 EUR",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.00005"),
        decimals=5,
        valuePerTick="$6.25",
    ),
    "RP": FutureDetail(
        symbol="RP",
        exchange="CME",
        name="Euro/British Pound",
        size="125000 EUR",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.00005"),
        decimals=5,
        valuePerTick="£6.25",
    ),
    "RY": FutureDetail(
        symbol="RY",
        exchange="CME",
        name="Euro/Japanese Yen",
        size="125000 EUR",
        months="HMUZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="¥1250",
    ),
    "RF": FutureDetail(
        symbol="RF",
        exchange="CME",
        name="Euro/Swiss Franc",
        size="125000 EUR",
        months="HMUZ",
        tick=Decimal("0.0001"),
        decimals=4,
        valuePerTick="CHF12.5",
    ),
    "SIR": FutureDetail(
        symbol="SIR",
        exchange="CME",
        name="Indian Rupee/USD",
        size="500 INR",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="$5",
    ),
    "6J": FutureDetail(
        symbol="6J",
        exchange="CME",
        name="Japanese Yen",
        size="12500000 JPY",
        months="FGHJKMNQUVXZ",
        tick=Decimal("5E-7"),
        decimals=7,
        valuePerTick="$6.25",
    ),
    "KRW": FutureDetail(
        symbol="KRW",
        exchange="CME",
        name="Korean Won",
        size="125000000 KRW",
        months="FGHJKMNQUVXZ",
        tick=Decimal("1E-7"),
        decimals=7,
        valuePerTick="$12.5",
    ),
    "6M": FutureDetail(
        symbol="6M",
        exchange="CME",
        name="Mexican Peso",
        size="500000 MXN",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.00001"),
        decimals=5,
        valuePerTick="$5",
    ),
    "M6A": FutureDetail(
        symbol="M6A",
        exchange="CME",
        name="Micro AUD/USD",
        size="10000 AUD",
        months="HMUZ",
        tick=Decimal("0.0001"),
        decimals=4,
        valuePerTick="$1",
    ),
    "MCD": FutureDetail(
        symbol="MCD",
        exchange="CME",
        name="Micro CAD/USD",
        size="10000 CAD",
        months="HMUZ",
        tick=Decimal("0.0001"),
        decimals=4,
        valuePerTick="$1",
    ),
    "MSF": FutureDetail(
        symbol="MSF",
        exchange="CME",
        name="Micro CHF/USD",
        size="12500 CHF",
        months="HMUZ",
        tick=Decimal("0.0001"),
        decimals=4,
        valuePerTick="$1.25",
    ),
    "M6E": FutureDetail(
        symbol="M6E",
        exchange="CME",
        name="Micro EUR/USD",
        size="12500 EUR",
        months="HMUZ",
        tick=Decimal("0.0001"),
        decimals=4,
        valuePerTick="$1.25",
    ),
    "M6B": FutureDetail(
        symbol="M6B",
        exchange="CME",
        name="Micro GBP/USD",
        size="6250 GBP",
        months="HMUZ",
        tick=Decimal("0.0001"),
        decimals=4,
        valuePerTick="$0.625",
    ),
    "MIR": FutureDetail(
        symbol="MIR",
        exchange="CME",
        name="Micro INR/USD",
        size="100 INR",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="$1",
    ),
    "6N": FutureDetail(
        symbol="6N",
        exchange="CME",
        name="New Zealand Dollar",
        size="100000 NZD",
        months="HMUZ",
        tick=Decimal("0.00005"),
        decimals=5,
        valuePerTick="$5",
    ),
    "6R": FutureDetail(
        symbol="6R",
        exchange="CME",
        name="Russian Ruble",
        size="2500000 RUB",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.000005"),
        decimals=6,
        valuePerTick="$12.5",
    ),
    "6Z": FutureDetail(
        symbol="6Z",
        exchange="CME",
        name="South African Rand",
        size="500000 ZAR",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.000025"),
        decimals=6,
        valuePerTick="$12.5",
    ),
    "SEK": FutureDetail(
        symbol="SEK",
        exchange="CME",
        name="Swedish Krona",
        size="2000000 SEK",
        months="HMUZ",
        tick=Decimal("0.00001"),
        decimals=5,
        valuePerTick="$20",
    ),
    "6S": FutureDetail(
        symbol="6S",
        exchange="CME",
        name="Swiss Franc",
        size="125000 CHF",
        months="HMUZ",
        tick=Decimal("0.00005"),
        decimals=5,
        valuePerTick="$6.25",
    ),
    "DX-M": FutureDetail(
        symbol="DX-M",
        exchange="ICEUS",
        name="US Dollar Index",
        size="1000 x Index Value",
        months="HMUZ",
        tick=Decimal("0.005"),
        decimals=3,
        valuePerTick="$5",
    ),
    "BZ": FutureDetail(
        symbol="BZ",
        exchange="NYMEX",
        name="Brent Last Day Financial",
        size="1000 barrels",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="$10",
    ),
    "GCL": FutureDetail(
        symbol="GCL",
        exchange="NYMEX",
        name="Crude Oil",
        size="1000 barrels",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="$10",
    ),
    "CLT": FutureDetail(
        symbol="CLT",
        exchange="NYMEX",
        name="Crude Oil TAS",
        size="10 (1 Futures contract)",
        months="FGHJKMNQUVXZ",
        tick=Decimal("1"),
        decimals=0,
        valuePerTick="$10",
    ),
    "QM": FutureDetail(
        symbol="QM",
        exchange="NYMEX",
        name="E-mini Crude Oil",
        size="500 barrels",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.025"),
        decimals=3,
        valuePerTick="$12.5",
    ),
    "GHO": FutureDetail(
        symbol="GHO",
        exchange="NYMEX",
        name="Heating Oil",
        size="42000 gallons",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.0001"),
        decimals=4,
        valuePerTick="$4.2",
    ),
    "HOT": FutureDetail(
        symbol="HOT",
        exchange="NYMEX",
        name="Heating Oil TAS",
        size="4 (1 Futures contract)",
        months="FGHJKMNQUVXZ",
        tick=Decimal("1"),
        decimals=0,
        valuePerTick="$4",
    ),
    "GNG": FutureDetail(
        symbol="GNG",
        exchange="NYMEX",
        name="HH Natural Gas",
        size="10000 mmBtu",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.001"),
        decimals=3,
        valuePerTick="$10",
    ),
    "QG": FutureDetail(
        symbol="QG",
        exchange="NYMEX",
        name="HH Natural Gas miNY",
        size="2500 mmBtu",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.005"),
        decimals=3,
        valuePerTick="$12.5",
    ),
    "NGT": FutureDetail(
        symbol="NGT",
        exchange="NYMEX",
        name="HH Natural Gas TAS",
        size="10 (1 Futures contract)",
        months="FGHJKMNQUVXZ",
        tick=Decimal("1"),
        decimals=0,
        valuePerTick="$10",
    ),
    "MCL": FutureDetail(
        symbol="MCL",
        exchange="NYMEX",
        name="Micro Crude Oil",
        size="100 barrels",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="$1",
    ),
    "MNG": FutureDetail(
        symbol="MNG",
        exchange="NYMEX",
        name="Micro Henry Hub Natural Gas",
        size="1000 MMBtu",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.001"),
        decimals=3,
        valuePerTick="$1",
    ),
    "HH": FutureDetail(
        symbol="HH",
        exchange="NYMEX",
        name="Natural Gas Last-day",
        size="10000 mmBtu",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.001"),
        decimals=3,
        valuePerTick="$10",
    ),
    "GRB": FutureDetail(
        symbol="GRB",
        exchange="NYMEX",
        name="RBOB Gasoline",
        size="42000 gallons",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.0001"),
        decimals=4,
        valuePerTick="$4.2",
    ),
    "RBT": FutureDetail(
        symbol="RBT",
        exchange="NYMEX",
        name="RBOB Gasoline TAS",
        size="4 (1 Futures contract)",
        months="FGHJKMNQUVXZ",
        tick=Decimal("1"),
        decimals=0,
        valuePerTick="$4",
    ),
    "ZN": FutureDetail(
        symbol="ZN",
        exchange="CBOT",
        name="10 Yr US T-Note",
        size="100000 USD",
        months="HMUZ",
        tick=Decimal("0.015625"),
        decimals=6,
        valuePerTick="$1562.5",
    ),
    "N1U": FutureDetail(
        symbol="N1U",
        exchange="CBOT",
        name="10-Year USD MAC Swap Futures",
        size="100000 USD",
        months="HMUZ",
        tick=Decimal("0.015625"),
        decimals=6,
        valuePerTick="$1562.5",
    ),
    "ZT": FutureDetail(
        symbol="ZT",
        exchange="CBOT",
        name="2 Yr US T-Note",
        size="20000 USD",
        months="HMUZ",
        tick=Decimal("0.00390625"),
        decimals=8,
        valuePerTick="$78.125",
    ),
    "ZQ": FutureDetail(
        symbol="ZQ",
        exchange="CBOT",
        name="30 Day Fed Fund",
        size="4167 x Contract IMM Index",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.0025"),
        decimals=4,
        valuePerTick="$10.4175",
    ),
    "ZB": FutureDetail(
        symbol="ZB",
        exchange="CBOT",
        name="30 Yr US T-Bonds",
        size="10000 USD",
        months="HMUZ",
        tick=Decimal("0.03125"),
        decimals=5,
        valuePerTick="$312.5",
    ),
    "Z3N": FutureDetail(
        symbol="Z3N",
        exchange="CBOT",
        name="3-Yr. T-Note",
        size="200000 USD",
        months="HMUZ",
        tick=Decimal("0.00390625"),
        decimals=8,
        valuePerTick="$781.25",
    ),
    "ZF": FutureDetail(
        symbol="ZF",
        exchange="CBOT",
        name="5 Yr T-Note",
        size="10000 USD",
        months="HMUZ",
        tick=Decimal("0.0078125"),
        decimals=7,
        valuePerTick="$78.125",
    ),
    "F1U": FutureDetail(
        symbol="F1U",
        exchange="CBOT",
        name="5-Year USD MAC Swap",
        size="10000 USD",
        months="HMUZ",
        tick=Decimal("0.0078125"),
        decimals=7,
        valuePerTick="$78.125",
    ),
    "CONF": FutureDetail(
        symbol="CONF",
        exchange="EUREX",
        name="CONF Fut",
        size="10000 CHF",
        months="HMUZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="€100",
    ),
    "FBTP": FutureDetail(
        symbol="FBTP",
        exchange="EUREX",
        name="EURO BTP FUTURES",
        size="100000 EUR",
        months="HMUZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="€1000",
    ),
    "FOAT": FutureDetail(
        symbol="FOAT",
        exchange="EUREX",
        name="EURO OAT FUTURE 8,5- 10,5 YEAR",
        size="100000 EUR",
        months="HMUZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="€1000",
    ),
    "FGBM": FutureDetail(
        symbol="FGBM",
        exchange="EUREX",
        name="EuroBobl",
        size="100000 EUR",
        months="HMUZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="€1000",
    ),
    "FGBL": FutureDetail(
        symbol="FGBL",
        exchange="EUREX",
        name="EuroBund",
        size="100000 EUR",
        months="HMUZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="€1000",
    ),
    "FGBX": FutureDetail(
        symbol="FGBX",
        exchange="EUREX",
        name="Euro-Buxl",
        size="100000 EUR",
        months="HMUZ",
        tick=Decimal("0.02"),
        decimals=2,
        valuePerTick="€2000",
    ),
    "10Y": FutureDetail(
        symbol="10Y",
        exchange="CBOT",
        name="Micro 10-Year Yield",
        size="1000 x current price",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.001"),
        decimals=3,
        valuePerTick="$1",
    ),
    "MTN": FutureDetail(
        symbol="MTN",
        exchange="CBOT",
        name="Micro Ultra 10-Year U.S. Treasury Note",
        size="10000 USD",
        months="HMUZ",
        tick=Decimal("0.015625"),
        decimals=6,
        valuePerTick="$156.25",
    ),
    "MWN": FutureDetail(
        symbol="MWN",
        exchange="CBOT",
        name="Micro Ultra U.S. Treasury Bond",
        size="10000 USD",
        months="HMUZ",
        tick=Decimal("0.03125"),
        decimals=5,
        valuePerTick="$312.5",
    ),
    "SR1": FutureDetail(
        symbol="SR1",
        exchange="CME",
        name="One-Month SOFR Futures",
        size="4167 x Contract IMM Index",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.0025"),
        decimals=4,
        valuePerTick="$10.4175",
    ),
    "FGBS": FutureDetail(
        symbol="FGBS",
        exchange="EUREX",
        name="Schatz",
        size="100000 EUR",
        months="HMUZ",
        tick=Decimal("0.005"),
        decimals=3,
        valuePerTick="€500",
    ),
    "FBTS": FutureDetail(
        symbol="FBTS",
        exchange="EUREX",
        name="Short-Term Euro-BTP Futures",
        size="100000 EUR",
        months="HMUZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="€1000",
    ),
    "S10Y": FutureDetail(
        symbol="S10Y",
        exchange="SMFE",
        name="Small 10YR US Treasury Yield",
        size="100 x current price",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="$1",
    ),
    "S2Y": FutureDetail(
        symbol="S2Y",
        exchange="SMFE",
        name="Small 2YR US Treasury Yield",
        size="100 x current price",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="$1",
    ),
    "S30Y": FutureDetail(
        symbol="S30Y",
        exchange="SMFE",
        name="Small 30YR US Treasury Yield",
        size="100 x current price",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="$1",
    ),
    "SR3": FutureDetail(
        symbol="SR3",
        exchange="CME",
        name="Three-Month SOFR Futures",
        size="2500 x Contract IMM Index",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.0025"),
        decimals=4,
        valuePerTick="$6.25",
    ),
    "TN": FutureDetail(
        symbol="TN",
        exchange="CBOT",
        name="Ultra 10-Year Note",
        size="100000 USD",
        months="HMUZ",
        tick=Decimal("0.015625"),
        decimals=6,
        valuePerTick="$1562.5",
    ),
    "UB": FutureDetail(
        symbol="UB",
        exchange="CBOT",
        name="Ultra T-Bond",
        size="100000 USD",
        months="HMUZ",
        tick=Decimal("0.03125"),
        decimals=5,
        valuePerTick="$3125",
    ),
    "AW": FutureDetail(
        symbol="AW",
        exchange="CBOT",
        name="Bloomberg Commodity Index",
        size="100 X Index Value",
        months="HMUZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="$1",
    ),
    "ZLT": FutureDetail(
        symbol="ZLT",
        exchange="CBOT",
        name="CBOT Bean Oil TAS",
        size="60000 pounds",
        months="FHKNQUVZ",
        tick=Decimal("0.0001"),
        decimals=4,
        valuePerTick="$6",
    ),
    "ZCT": FutureDetail(
        symbol="ZCT",
        exchange="CBOT",
        name="CBOT Corn TAS",
        size="5000 bushels",
        months="HKNUZ",
        tick=Decimal("0.0025"),
        decimals=4,
        valuePerTick="$12.5",
    ),
    "ZST": FutureDetail(
        symbol="ZST",
        exchange="CBOT",
        name="CBOT Soybean TAS",
        size="5000 bushels",
        months="FHKNQUX",
        tick=Decimal("0.0025"),
        decimals=4,
        valuePerTick="$12.5",
    ),
    "ZMT": FutureDetail(
        symbol="ZMT",
        exchange="CBOT",
        name="CBOT Soymeal TAS",
        size="100 short tons",
        months="FHKNQUVZ",
        tick=Decimal("0.1"),
        decimals=1,
        valuePerTick="$10",
    ),
    "ZWT": FutureDetail(
        symbol="ZWT",
        exchange="CBOT",
        name="CBOT Wheat TAS",
        size="5000 bushels",
        months="HKNUZ",
        tick=Decimal("0.0025"),
        decimals=4,
        valuePerTick="$12.5",
    ),
    "ZC": FutureDetail(
        symbol="ZC",
        exchange="CBOT",
        name="Corn",
        size="5000 bushels",
        months="HKNUZ",
        tick=Decimal("0.0025"),
        decimals=4,
        valuePerTick="$12.5",
    ),
    "KE": FutureDetail(
        symbol="KE",
        exchange="CBOT",
        name="KC Wheat",
        size="5000 bushels",
        months="HKNUZ",
        tick=Decimal("0.0025"),
        decimals=4,
        valuePerTick="$12.5",
    ),
    "XC": FutureDetail(
        symbol="XC",
        exchange="CBOT",
        name="Mini Corn",
        size="1000 bushels",
        months="HKNUZ",
        tick=Decimal("0.00125"),
        decimals=5,
        valuePerTick="$1.25",
    ),
    "XB": FutureDetail(
        symbol="XB",
        exchange="CBOT",
        name="Mini Soybeans",
        size="1000 bushels",
        months="FHKNQUX",
        tick=Decimal("0.00125"),
        decimals=5,
        valuePerTick="$1.25",
    ),
    "XW": FutureDetail(
        symbol="XW",
        exchange="CBOT",
        name="Mini Wheat",
        size="1000 bushels",
        months="HKNUZ",
        tick=Decimal("0.00125"),
        decimals=5,
        valuePerTick="$1.25",
    ),
    "MWE": FutureDetail(
        symbol="MWE",
        exchange="MGE",
        name="Minneapolis Wheat",
        size="5000 bushels",
        months="HKNUZ",
        tick=Decimal("0.0025"),
        decimals=4,
        valuePerTick="$12.5",
    ),
    "ZO": FutureDetail(
        symbol="ZO",
        exchange="CBOT",
        name="Oats",
        size="5000 bushels",
        months="HKNUZ",
        tick=Decimal("0.0025"),
        decimals=4,
        valuePerTick="$12.5",
    ),
    "ZR": FutureDetail(
        symbol="ZR",
        exchange="CBOT",
        name="Rough Rice",
        size="2000 cwt",
        months="FHKNUX",
        tick=Decimal("0.005"),
        decimals=3,
        valuePerTick="$10",
    ),
    "ZL": FutureDetail(
        symbol="ZL",
        exchange="CBOT",
        name="Soybean Oil",
        size="60000 pounds",
        months="FHKNQUVZ",
        tick=Decimal("0.0001"),
        decimals=4,
        valuePerTick="$6",
    ),
    "ZS": FutureDetail(
        symbol="ZS",
        exchange="CBOT",
        name="Soybeans",
        size="5000 bushels",
        months="FHKNQUX",
        tick=Decimal("0.0025"),
        decimals=4,
        valuePerTick="$12.5",
    ),
    "ZM": FutureDetail(
        symbol="ZM",
        exchange="CBOT",
        name="Soymeal",
        size="100 short tons",
        months="FHKNQUVZ",
        tick=Decimal("0.1"),
        decimals=1,
        valuePerTick="$10",
    ),
    "ZW": FutureDetail(
        symbol="ZW",
        exchange="CBOT",
        name="Wheat",
        size="5000 bushels",
        months="HKNUZ",
        tick=Decimal("0.0025"),
        decimals=4,
        valuePerTick="$12.5",
    ),
    "VX": FutureDetail(
        symbol="VX",
        exchange="CFE",
        name="CBOE Volatility Index (VIX)",
        size="1000 X Index Value",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.05"),
        decimals=2,
        valuePerTick="$50",
    ),
    "BTC": FutureDetail(
        symbol="BTC",
        exchange="CME",
        name="CME Bitcoin Futures",
        size="5 Bitcoin",
        months="FGHJKMNQUVXZ",
        tick=Decimal("5"),
        decimals=0,
        valuePerTick="$25",
    ),
    "ETH": FutureDetail(
        symbol="ETH",
        exchange="CME",
        name="CME Ether Futures",
        size="50 Ether",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.5"),
        decimals=1,
        valuePerTick="$25",
    ),
    "MBT": FutureDetail(
        symbol="MBT",
        exchange="CME",
        name="CME Micro Bitcoin",
        size="0.1 Bitcoin",
        months="FGHJKMNQUVXZ",
        tick=Decimal("5"),
        decimals=0,
        valuePerTick="$0.5",
    ),
    "FDAX": FutureDetail(
        symbol="FDAX",
        exchange="EUREX",
        name="DAX",
        size="25 X Index Value",
        months="HMUZ",
        tick=Decimal("1"),
        decimals=0,
        valuePerTick="€25",
    ),
    "RE": FutureDetail(
        symbol="RE",
        exchange="CBOT",
        name="DJ Real Estate Futures",
        size="100 X Index Value",
        months="HMUZ",
        tick=Decimal("0.1"),
        decimals=1,
        valuePerTick="$10",
    ),
    "FSTX": FutureDetail(
        symbol="FSTX",
        exchange="EUREX",
        name="DJ STOXX 50 Index",
        size="10 X Index Value",
        months="HMUZ",
        tick=Decimal("1"),
        decimals=0,
        valuePerTick="€10",
    ),
    "YM": FutureDetail(
        symbol="YM",
        exchange="CBOT",
        name="E-Mini Dow $5",
        size="5 X Index Value",
        months="HMUZ",
        tick=Decimal("1"),
        decimals=0,
        valuePerTick="$5",
    ),
    "NQ": FutureDetail(
        symbol="NQ",
        exchange="CME",
        name="E-Mini NASDAQ 100",
        size="20 X Index Value",
        months="HMUZ",
        tick=Decimal("0.25"),
        decimals=2,
        valuePerTick="$5",
    ),
    "RTY": FutureDetail(
        symbol="RTY",
        exchange="CME",
        name="E-mini Russell 2000 Index",
        size="50 X Index Value",
        months="HMUZ",
        tick=Decimal("0.1"),
        decimals=1,
        valuePerTick="$5",
    ),
    "ES": FutureDetail(
        symbol="ES",
        exchange="CME",
        name="E-Mini S&P 500",
        size="50 X Index Value",
        months="HMUZ",
        tick=Decimal("0.25"),
        decimals=2,
        valuePerTick="$12.5",
    ),
    "EMD": FutureDetail(
        symbol="EMD",
        exchange="CME",
        name="E-Mini S&P MIDCAP 400",
        size="100 x Index Value",
        months="HMUZ",
        tick=Decimal("0.1"),
        decimals=1,
        valuePerTick="$10",
    ),
    "FESX": FutureDetail(
        symbol="FESX",
        exchange="EUREX",
        name="Euro STOXX 50 Index",
        size="10 X Index Value",
        months="HMUZ",
        tick=Decimal("1"),
        decimals=0,
        valuePerTick="€10",
    ),
    "FDXS": FutureDetail(
        symbol="FDXS",
        exchange="EUREX",
        name="Micro Dax",
        size="1 X Index Value",
        months="HMUZ",
        tick=Decimal("1"),
        decimals=0,
        valuePerTick="€1",
    ),
    "MYM": FutureDetail(
        symbol="MYM",
        exchange="CBOT",
        name="Micro E-mini Dow",
        size="0.5 X Index Value",
        months="HMUZ",
        tick=Decimal("1"),
        decimals=0,
        valuePerTick="$0.5",
    ),
    "MNQ": FutureDetail(
        symbol="MNQ",
        exchange="CME",
        name="Micro E-mini Nasdaq-100",
        size="2 X Index Value",
        months="HMUZ",
        tick=Decimal("0.25"),
        decimals=2,
        valuePerTick="$0.5",
    ),
    "M2K": FutureDetail(
        symbol="M2K",
        exchange="CME",
        name="Micro E-mini Russell 2000",
        size="5 X Index Value",
        months="HMUZ",
        tick=Decimal("0.1"),
        decimals=1,
        valuePerTick="$0.5",
    ),
    "MES": FutureDetail(
        symbol="MES",
        exchange="CME",
        name="Micro E-mini S&P 500",
        size="5 X Index Value",
        months="HMUZ",
        tick=Decimal("0.25"),
        decimals=2,
        valuePerTick="$1.25",
    ),
    "MET": FutureDetail(
        symbol="MET",
        exchange="CME",
        name="Micro Ether",
        size="1 (0.10 Ether)",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.5"),
        decimals=1,
        valuePerTick="$0.5",
    ),
    "FNG": FutureDetail(
        symbol="FNG",
        exchange="ICEUSRP",
        name="MICRO NYSE Fang+ Index",
        size="5 X Index Value",
        months="HMUZ",
        tick=Decimal("0.2"),
        decimals=1,
        valuePerTick="$1",
    ),
    "FSXE": FutureDetail(
        symbol="FSXE",
        exchange="EUREX",
        name="Micro-EURO STOXX 50",
        size="1 X Index Value",
        months="HMUZ",
        tick=Decimal("1"),
        decimals=0,
        valuePerTick="€1",
    ),
    "VXM": FutureDetail(
        symbol="VXM",
        exchange="CFE",
        name="Mini Cboe Volatility Index Futures",
        size="100 X Index Value",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.05"),
        decimals=2,
        valuePerTick="$5",
    ),
    "FDXM": FutureDetail(
        symbol="FDXM",
        exchange="EUREX",
        name="Mini Dax",
        size="5 X Index Value",
        months="HMUZ",
        tick=Decimal("1"),
        decimals=0,
        valuePerTick="€5",
    ),
    "MFS": FutureDetail(
        symbol="MFS",
        exchange="ICEUS",
        name="Mini MSCI EAFE Index",
        size="50 X Index Value",
        months="HMUZ",
        tick=Decimal("0.1"),
        decimals=1,
        valuePerTick="$5",
    ),
    "MME": FutureDetail(
        symbol="MME",
        exchange="ICEUS",
        name="MSCI Emerging Markets Index",
        size="50 X Index Value",
        months="HMUZ",
        tick=Decimal("0.1"),
        decimals=1,
        valuePerTick="$5",
    ),
    "BIT": FutureDetail(
        symbol="BIT",
        exchange="Coinbase Derivatives",
        name="Nano Bitcoin",
        size="0.01 Bitcoin",
        months="FGHJKMNQUVXZ",
        tick=Decimal("5"),
        decimals=0,
        valuePerTick="$0.05",
    ),
    "ET": FutureDetail(
        symbol="ET",
        exchange="Coinbase Derivatives",
        name="Nano Ether",
        size="0.1 Ether",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.5"),
        decimals=1,
        valuePerTick="$0.05",
    ),
    "NKD": FutureDetail(
        symbol="NKD",
        exchange="CME",
        name="Nikkei 225/USD",
        size="5 X Index Value",
        months="HMUZ",
        tick=Decimal("5"),
        decimals=0,
        valuePerTick="$25",
    ),
    "NIY": FutureDetail(
        symbol="NIY",
        exchange="CME",
        name="Nikkei 225/Yen",
        size="500 X Index Value",
        months="FGHJKMNQUVXZ",
        tick=Decimal("5"),
        decimals=0,
        valuePerTick="¥2500",
    ),
    "FTDX": FutureDetail(
        symbol="FTDX",
        exchange="EUREX",
        name="TECDAX",
        size="10 X Index Value",
        months="HMUZ",
        tick=Decimal("0.5"),
        decimals=1,
        valuePerTick="€5",
    ),
    "VXT": FutureDetail(
        symbol="VXT",
        exchange="CFE",
        name="Volatility Index TAS",
        size="1000 (1 Futures contract)",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="$10",
    ),
    "FVS": FutureDetail(
        symbol="FVS",
        exchange="EUREX",
        name="VSTOXX",
        size="100 X Index Value",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.05"),
        decimals=2,
        valuePerTick="€5",
    ),
    "GF": FutureDetail(
        symbol="GF",
        exchange="CME",
        name="Feeder Cattle",
        size="500 pounds",
        months="FHJKQUVX",
        tick=Decimal("0.025"),
        decimals=3,
        valuePerTick="$12.5",
    ),
    "HE": FutureDetail(
        symbol="HE",
        exchange="CME",
        name="Lean Hogs",
        size="400 pounds",
        months="GJKMNQVZ",
        tick=Decimal("0.025"),
        decimals=3,
        valuePerTick="$10",
    ),
    "LE": FutureDetail(
        symbol="LE",
        exchange="CME",
        name="Live Cattle",
        size="400 pounds",
        months="GJMQVZ",
        tick=Decimal("0.025"),
        decimals=3,
        valuePerTick="$10",
    ),
    "PRK": FutureDetail(
        symbol="PRK",
        exchange="CME",
        name="Pork Cutout Futures",
        size="400 pounds",
        months="GJKMNQVZ",
        tick=Decimal("0.025"),
        decimals=3,
        valuePerTick="$10",
    ),
    "GHG": FutureDetail(
        symbol="GHG",
        exchange="COMEX",
        name="Copper",
        size="25000 pounds",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.0005"),
        decimals=4,
        valuePerTick="$12.5",
    ),
    "MGC": FutureDetail(
        symbol="MGC",
        exchange="COMEX",
        name="E-micro Gold",
        size="10 ounces",
        months="GJMQVZ",
        tick=Decimal("0.1"),
        decimals=1,
        valuePerTick="$1",
    ),
    "GGC": FutureDetail(
        symbol="GGC",
        exchange="COMEX",
        name="Gold",
        size="100 ounces",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.1"),
        decimals=1,
        valuePerTick="$10",
    ),
    "MHG": FutureDetail(
        symbol="MHG",
        exchange="NYMEX",
        name="Micro Copper",
        size="2500 pounds",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.0005"),
        decimals=4,
        valuePerTick="$1.25",
    ),
    "SIL": FutureDetail(
        symbol="SIL",
        exchange="COMEX",
        name="Micro Silver",
        size="1000 troy ounces",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.005"),
        decimals=3,
        valuePerTick="$5",
    ),
    "QC": FutureDetail(
        symbol="QC",
        exchange="COMEX",
        name="miNY Copper",
        size="12500 pounds",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.002"),
        decimals=3,
        valuePerTick="$25",
    ),
    "QO": FutureDetail(
        symbol="QO",
        exchange="COMEX",
        name="miNY Gold",
        size="50 ounces",
        months="GJMQVZ",
        tick=Decimal("0.25"),
        decimals=2,
        valuePerTick="$12.5",
    ),
    "QI": FutureDetail(
        symbol="QI",
        exchange="COMEX",
        name="miNY Silver",
        size="2500 ounces",
        months="FHKNUZ",
        tick=Decimal("0.0125"),
        decimals=4,
        valuePerTick="$31.25",
    ),
    "GPA": FutureDetail(
        symbol="GPA",
        exchange="NYMEX",
        name="Palladium",
        size="100 ounces",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.5"),
        decimals=1,
        valuePerTick="$50",
    ),
    "GPL": FutureDetail(
        symbol="GPL",
        exchange="NYMEX",
        name="Platinum",
        size="50 ounces",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.1"),
        decimals=1,
        valuePerTick="$5",
    ),
    "GSI": FutureDetail(
        symbol="GSI",
        exchange="COMEX",
        name="Silver",
        size="5000 ounces",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.005"),
        decimals=3,
        valuePerTick="$25",
    ),
    "BLK": FutureDetail(
        symbol="BLK",
        exchange="CME",
        name="Block Cheese Futures",
        size="20000 Pounds",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.001"),
        decimals=3,
        valuePerTick="$20",
    ),
    "CB": FutureDetail(
        symbol="CB",
        exchange="CME",
        name="Cash-Settled Butter",
        size="20000 Pounds",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.00025"),
        decimals=5,
        valuePerTick="$5",
    ),
    "CSC": FutureDetail(
        symbol="CSC",
        exchange="CME",
        name="Cash-Settled Cheese",
        size="20000 pounds",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.001"),
        decimals=3,
        valuePerTick="$20",
    ),
    "DA": FutureDetail(
        symbol="DA",
        exchange="CME",
        name="Class III Milk",
        size="2000 pounds",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="$20",
    ),
    "DK": FutureDetail(
        symbol="DK",
        exchange="CME",
        name="Class IV Milk Fut",
        size="2000 pounds",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.01"),
        decimals=2,
        valuePerTick="$20",
    ),
    "CC-M": FutureDetail(
        symbol="CC-M",
        exchange="ICEUS",
        name="Cocoa",
        size="10 metric tonnes",
        months="HKNUZ",
        tick=Decimal("1"),
        decimals=0,
        valuePerTick="$10",
    ),
    "CC-M-S": FutureDetail(
        symbol="CC-M-S",
        exchange="ICEUS",
        name="Cocoa TAS",
        size="10 (1 Futures contract)",
        months="HKNUZ",
        tick=Decimal("1"),
        decimals=0,
        valuePerTick="$10",
    ),
    "KC-M": FutureDetail(
        symbol="KC-M",
        exchange="ICEUS",
        name="Coffee",
        size="37500 pounds",
        months="HKNUZ",
        tick=Decimal("0.0005"),
        decimals=4,
        valuePerTick="$18.75",
    ),
    "KC-M-S": FutureDetail(
        symbol="KC-M-S",
        exchange="ICEUS",
        name='Coffee "C" TAS',
        size="37500 (1 Futures contract)",
        months="HKNUZ",
        tick=Decimal("0.0005"),
        decimals=4,
        valuePerTick="$18.75",
    ),
    "CT-M-S": FutureDetail(
        symbol="CT-M-S",
        exchange="ICEUS",
        name="Cotton No. 2 TAS",
        size="50000 (1 Futures contract)",
        months="HKNVZ",
        tick=Decimal("0.0001"),
        decimals=4,
        valuePerTick="$5",
    ),
    "CT-M": FutureDetail(
        symbol="CT-M",
        exchange="ICEUS",
        name="Cotton No.2",
        size="50000 pounds",
        months="HKNVZ",
        tick=Decimal("0.0001"),
        decimals=4,
        valuePerTick="$5",
    ),
    "DY": FutureDetail(
        symbol="DY",
        exchange="CME",
        name="Dry Whey",
        size="44000 Pounds",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.00025"),
        decimals=5,
        valuePerTick="$11",
    ),
    "OJ-M-S": FutureDetail(
        symbol="OJ-M-S",
        exchange="ICEUS",
        name="FCOJ-A TAS",
        size="15000 (1 Futures contract)",
        months="FHKNUX",
        tick=Decimal("0.0005"),
        decimals=4,
        valuePerTick="$7.5",
    ),
    "OJ-M": FutureDetail(
        symbol="OJ-M",
        exchange="ICEUS",
        name="Frozen OJ",
        size="15000 15K lbs",
        months="FHKNUX",
        tick=Decimal("0.0005"),
        decimals=4,
        valuePerTick="$7.5",
    ),
    "LBR": FutureDetail(
        symbol="LBR",
        exchange="CME",
        name="Lumber Futures",
        size="27500 board feet",
        months="FHKNUX",
        tick=Decimal("0.5"),
        decimals=1,
        valuePerTick="$13750",
    ),
    "NF": FutureDetail(
        symbol="NF",
        exchange="CME",
        name="Nonfat Dry Milk",
        size="44000 Pounds",
        months="FGHJKMNQUVXZ",
        tick=Decimal("0.00025"),
        decimals=5,
        valuePerTick="$11",
    ),
    "SB-M": FutureDetail(
        symbol="SB-M",
        exchange="ICEUS",
        name="Sugar No. 11",
        size="112000 pounds",
        months="HKNV",
        tick=Decimal("0.0001"),
        decimals=4,
        valuePerTick="$11.2",
    ),
    "SB-M-S": FutureDetail(
        symbol="SB-M-S",
        exchange="ICEUS",
        name="Sugar No. 11 TAS",
        size="112000 (1 Futures contract)",
        months="HKNV",
        tick=Decimal("0.0001"),
        decimals=4,
        valuePerTick="$11.2",
    ),
}
